---
- name: Generate data ibmc for server xfusion PM
  hosts: all_server
  connection: local
  gather_facts: false
  tasks:
    - name: "Create folder {{ inventory_hostname }}"
      file:
        path: "{{playbook_dir}}/{{ inventory_hostname }}"
        state: directory
    - name: Get Data
      community.general.redfish_info:
        category: Systems
          #command: GetSystemInventory
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result
    - name: Print chassis value
      debug:
        #msg: "{{ result.redfish_facts.firmware.entries.0.Id }} {{ result.redfish_facts.firmware.entries.0.Version }}"
        var: result
