---
- name: Generate data ibmc for server xfusion PM
  hosts: all_server
  connection: local
  gather_facts: false
  tasks:
    - name: "Create folder {{ inventory_hostname }}"
      file:
        path: "{{playbook_dir}}/{{ inventory_hostname }}"
        state: directory
    - name: Get chassis inventory information
      community.general.redfish_info:
        category: Chassis
        command: GetChassisInventory
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result
    - name: Print chassis value
      debug:
        var: result
