---
- name: "Write chassis inventory result on {{playbook_dir}}/PM/{{ inventory_hostname }}/{{ inventory_hostname }}_chassis.csv" 
  blockinfile:
    path: "{{playbook_dir}}/PM/{{ inventory_hostname }}/{{ inventory_hostname }}_chassis.csv"
    create: true
    block: |
      ID,{{ inventory_hostname }}
      Model,{{ chassis.redfish_facts.chassis.entries.0.Model }}
      Serial Number,{{ chassis.redfish_facts.chassis.entries.0.SerialNumber }}
      IP MGMT,{{ ansible_host }}
      Firmware,{{ firmware.redfish_facts.firmware.entries.0.Version }}
      CPU Utilization,
      Memory Utilization,
      Timestamp,
  delegate_to: localhost
  become: no
